# Generated by Django 5.2.3 on 2025-07-16 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='deccription',
            new_name='description',
        ),
    ]
